name: Build and Deploy Bauphonic Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: bauphonicreg.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t bauphonicreg.azurecr.io/bauphonic:latest .
        docker push bauphonicreg.azurecr.io/bauphonic:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: bauphonic
        images: bauphonicreg.azurecr.io/bauphonic:latest